apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      readinessGates:
      - conditionType: target-health.alb.ingress.k8s.aws/load-balancer-any-tg-ready    
      containers:
        resources:
          limits:
            cpu: 250m
          requests:
            cpu: 250m       
      - image: public.ecr.aws/p2a6g7m7/website:latest
        name: guestbook-ui
        ports:
        - containerPort: 8089   
