kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: aws-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: '/'
   #external-dns.alpha.kubernetes.io/hostname: guestbook-ui.ocpp-test.com
  name: ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: guestbook-ui
          servicePort: 8089
        path: /*
